title: NEET Advisor
description: An Initiative of Leopride Career Solutions


permalink: /blog/:title/


rzp-key: rzp_live_5l5MyQbw9aux1L
#rzp-neet-key: rzp_live_LLG1Bxq7atk0FU

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

# These details are for opengraph tags
social:
  name: LeoPride Consultants
  links:
    - https://www.facebook.com/leopride.in/
    - https://www.linkedin.com/company/14512687/
    - https://www.instagram.com/leopridecareersolutions/
    - https://www.youtube.com/channel/UCiJqbK5EeRtijkCgqwP5e4A

facebook:
  app_id: 272085763872601
  # publisher: 1234
  # admins: 1234



destination: public


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
